---
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
#   image: gcr.io/kaniko-project/executor:debug
    image: gcr.io/kaniko-project/executor:v0.13.0
    args: ["--context=git://github.com/dkelim1/dkelim1-app",
            "--destination=dkelim1/kaniko-demo"]
#           "--no-push"]
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
